package Models;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-12T07:01:26.498-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://localhost/RestaurantService", name = "RestaurantService")
@XmlSeeAlso({ObjectFactory.class})
public interface RestaurantService {

    @WebResult(name = "restaurant", targetNamespace = "")
    @RequestWrapper(localName = "getRestaurant", targetNamespace = "http://localhost/RestaurantService", className = "Models.GetRestaurant")
    @WebMethod
    @ResponseWrapper(localName = "getRestaurantResponse", targetNamespace = "http://localhost/RestaurantService", className = "Models.GetRestaurantResponse")
    public java.util.List<Models.Restaurant> getRestaurant();

    @WebResult(name = "menuItem", targetNamespace = "")
    @RequestWrapper(localName = "getMenuItem", targetNamespace = "http://localhost/RestaurantService", className = "Models.GetMenuItem")
    @WebMethod
    @ResponseWrapper(localName = "getMenuItemResponse", targetNamespace = "http://localhost/RestaurantService", className = "Models.GetMenuItemResponse")
    public java.util.List<Models.MenuItem> getMenuItem(
        @WebParam(name = "restaurantName", targetNamespace = "")
        java.lang.String restaurantName
    );
}
