package Models;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-12T07:01:26.517-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "RestaurantService", 
                  wsdlLocation = "file:/C:/Users/nnickerson/Documents/Java3/jaxws_exercise/src/Models/RestaurantService.wsdl",
                  targetNamespace = "http://service/") 
public class RestaurantService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service/", "RestaurantService");
    public final static QName RestaurantImplPort = new QName("http://service/", "RestaurantImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nnickerson/Documents/Java3/jaxws_exercise/src/Models/RestaurantService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RestaurantService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nnickerson/Documents/Java3/jaxws_exercise/src/Models/RestaurantService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RestaurantService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RestaurantService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RestaurantService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RestaurantService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RestaurantService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RestaurantService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RestaurantService
     */
    @WebEndpoint(name = "RestaurantImplPort")
    public RestaurantService getRestaurantImplPort() {
        return super.getPort(RestaurantImplPort, RestaurantService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RestaurantService
     */
    @WebEndpoint(name = "RestaurantImplPort")
    public RestaurantService getRestaurantImplPort(WebServiceFeature... features) {
        return super.getPort(RestaurantImplPort, RestaurantService.class, features);
    }

}
